org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false

# Disable Kotlin incremental compilation cross-drive relative path calculations
kotlin.incremental=false
kotlin.incremental.useClasspathSnapshot=false

MAPS_API_KEY=AIzaSyC-7JjgSXDrqNF1BMMnlvKtgRPS6_98uP8

